name: Deploy to EC2 via CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Make deploy.sh executable
      - name: Make deploy.sh executable
        run: chmod +x synergy-backend/scripts/deploy.sh

      # 3️⃣ Archive backend only
      - name: Archive backend
        run: zip -r app.zip synergy-backend/

      # 4️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 5️⃣ Upload zip to S3
      - name: Upload to S3
        run: aws s3 cp app.zip s3://credit-app-backend-auto/app.zip

      # 6️⃣ Deploy with CodeDeploy
      - name: Deploy with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name credit_app_backend \
            --deployment-group-name credit_app_backend_DG \
            --s3-location bucket=credit-app-backend-auto,key=app.zip,bundleType=zip
